var express = require('express');
var router = express.Router();

var db = require('../queries');

router.get(   '/docSpec/all',   db.getAll_docSpec); // GET    /docSpec/all without BODY
router.get(   '/docSpec/',  db.getSingle_docSpec);  // GET    /docSpec/?cSpec=... without BODY
router.post(  '/docSpec',   db.create_docSpec);     // POST   /docSpec with BODY: spec=...&spec_en=...
router.put(   '/docSpec/',  db.update_docSpec);     // PUT    /docSpec with BODY: cSpec=...&spec=...&spec_en=...
router.delete('/docSpec/',  db.remove_docSpec);     // DELETE /docSpec with BODY: cSpec=...

router.get(   '/doc/all',   db.getAll_doc); // GET    /doc/all without BODY
router.get(   '/doc/',  db.getSingle_doc);  // GET    /doc/?cDoc=... without BODY
router.post(  '/doc',   db.create_doc);     // POST   /doc with BODY: cSpec=...&pId=...&cState=...&docN=...&docDate=...&docEnd=...&docAuth=...&Memo=...
router.put(   '/doc/',  db.update_doc);     // PUT    /doc with BODY: cDoc=...&cSpec=...&pId=...&cState=...&docN=...&docDate=...&docEnd=...&docAuth=...&Memo=...
router.delete('/doc/',  db.remove_doc);     // DELETE /doc with BODY: cDoc=...

router.get(   '/State/all',   db.getAll_State); // GET    /State/all without BODY
router.get(   '/State/',  db.getSingle_State);  // GET    /State/?cState=... without BODY
router.post(  '/State',   db.create_State);     // POST   /State with BODY: State=...&State_en=...
router.put(   '/State/',  db.update_State);     // PUT    /State with BODY: cState=...&State=...&State_en=...
router.delete('/State/',  db.remove_State);     // DELETE /State with BODY: cState=...

router.get(   '/person/all',   db.getAll_person); // GET    /person/all without BODY
router.get(   '/person/',  db.getSingle_person);  // GET    /person/?pId=... without BODY
router.post(  '/person',   db.create_person);     // POST   /person with BODY: pId=...&cState=...&shortName=...&fullName=...&legalName=...&bornDate=...&sexId=...
router.put(   '/person/',  db.update_person);     // PUT    /person with BODY: pId=...&cState=...&shortName=...&fullName=...&legalName=...&bornDate=...&sexId=...
router.delete('/person/',  db.remove_person);     // DELETE /person with BODY: pId=...

router.get(   '/photoData/all',   db.getAll_photoData); // GET    /photoData/all without BODY
router.get(   '/photoData/',  db.getSingle_photoData);  // GET    /photoData/?pId=... without BODY
router.post(  '/photoData',   db.create_photoData);     // POST   /photoData with BODY: pId=...&cPhoto=...&photo=...
router.put(   '/photoData/',  db.update_photoData);     // PUT    /photoData with BODY: pId=...&cPhoto=...&photo=...
router.delete('/photoData/',  db.remove_photoData);     // DELETE /photoData with BODY: pId=...

router.get(   '/photoSpec/all',   db.getAll_photoSpec); // GET    /photoSpec/all without BODY
router.get(   '/photoSpec/',  db.getSingle_photoSpec);  // GET    /photoSpec/?cPhoto=... without BODY
router.post(  '/photoSpec',   db.create_photoSpec);     // POST   /photoSpec with BODY: photoSpec=...
router.put(   '/photoSpec/',  db.update_photoSpec);     // PUT    /photoSpec with BODY: cPhoto=...&photoSpec=...
router.delete('/photoSpec/',  db.remove_photoSpec);     // DELETE /photoSpec with BODY: cPhoto=...

router.get(   '/audioDatа/all',   db.getAll_audioDatа); // GET    /audioDatа/all without BODY
router.get(   '/audioDatа/',  db.getSingle_audioDatа);  // GET    /audioDatа/?pId=... without BODY
router.post(  '/audioDatа',   db.create_audioDatа);     // POST   /audioDatа with BODY: pId=...&audioFull=...&audioMemo=...&Memo=...
router.put(   '/audioDatа/',  db.update_audioDatа);     // PUT    /audioDatа with BODY: pId=...&audioFull=...&audioMemo=...&Memo=...
router.delete('/audioDatа/',  db.remove_audioDatа);     // DELETE /audioDatа with BODY: pId=...

router.get(   '/operator/all',   db.getAll_operator); // GET    /operator/all without BODY
router.get(   '/operator/',  db.getSingle_operator);  // GET    /operator/?cOper=... without BODY
router.post(  '/operator',   db.create_operator);     // POST   /operator with BODY: cRule=...&cPoint=...&Stuff=...&Stuff_en=...&key=...&phrase=...&stateId=...
router.put(   '/operator/',  db.update_operator);     // PUT    /operator with BODY: cOper=...&cRule=...&cPoint=...&Stuff=...&Stuff_en=...&key=...&phrase=...&stateId=...
router.delete('/operator/',  db.remove_operator);     // DELETE /operator with BODY: cOper=...

router.get(   '/regPoint/all',   db.getAll_regPoint); // GET    /regPoint/all without BODY
router.get(   '/regPoint/',  db.getSingle_regPoint);  // GET    /regPoint/?cPoint=... without BODY
router.post(  '/regPoint',   db.create_regPoint);     // POST   /regPoint with BODY: cState=...&point=...&point_en=...&location=...&location_en=...
router.put(   '/regPoint/',  db.update_regPoint);     // PUT    /regPoint with BODY: cPoint=...&cState=...&point=...&point_en=...&location=...&location_en=...
router.delete('/regPoint/',  db.remove_regPoint);     // DELETE /regPoint with BODY: cPoint=...

router.get(   '/opRule/all',   db.getAll_opRule); // GET    /opRule/all without BODY
router.get(   '/opRule/',  db.getSingle_opRule);  // GET    /opRule/?cRule=... without BODY
router.post(  '/opRule',   db.create_opRule);     // POST   /opRule with BODY: Rule=...&Rule_en=...
router.put(   '/opRule/',  db.update_opRule);     // PUT    /opRule with BODY: cRule=...&Rule=...&Rule_en=...
router.delete('/opRule/',  db.remove_opRule);     // DELETE /opRule with BODY: cRule=...

router.get(   '/Contact/all',   db.getAll_Contact); // GET    /Contact/all without BODY
router.get(   '/Contact/',  db.getSingle_Contact);  // GET    /Contact/?cContact=... without BODY
router.post(  '/Contact',   db.create_Contact);     // POST   /Contact with BODY: cAgent=...&pId=...&key=...&phrase=...&Memo=...&stateId=...
router.put(   '/Contact/',  db.update_Contact);     // PUT    /Contact with BODY: cContact=...&cAgent=...&pId=...&key=...&phrase=...&Memo=...&stateId=...
router.delete('/Contact/',  db.remove_Contact);     // DELETE /Contact with BODY: cContact=...

router.get(   '/Agent/all',   db.getAll_Agent); // GET    /Agent/all without BODY
router.get(   '/Agent/',  db.getSingle_Agent);  // GET    /Agent/?cAgent=... without BODY
router.post(  '/Agent',   db.create_Agent);     // POST   /Agent with BODY: Agent=...&Memo=...
router.put(   '/Agent/',  db.update_Agent);     // PUT    /Agent with BODY: cAgent=...&Agent=...&Memo=...
router.delete('/Agent/',  db.remove_Agent);     // DELETE /Agent with BODY: cAgent=...

router.get(   '/access/all',   db.getAll_access); // GET    /access/all without BODY
router.get(   '/access/',  db.getSingle_access);  // GET    /access/?cOper=...&pId=... without BODY
router.post(  '/access',   db.create_access);     // POST   /access with BODY: cOper=...&pId=...&stateId=...
router.put(   '/access/',  db.update_access);     // PUT    /access with BODY: cOper=...&pId=...&stateId=...
router.delete('/access/',  db.remove_access);     // DELETE /access with BODY: cOper=...&pId=...

router.get(   '/docImage/all',   db.getAll_docImage); // GET    /docImage/all without BODY
router.get(   '/docImage/',  db.getSingle_docImage);  // GET    /docImage/?pageN=... without BODY
router.post(  '/docImage',   db.create_docImage);     // POST   /docImage with BODY: pageN=...&cDoc=...&image=...
router.put(   '/docImage/',  db.update_docImage);     // PUT    /docImage with BODY: pageN=...&cDoc=...&image=...
router.delete('/docImage/',  db.remove_docImage);     // DELETE /docImage with BODY: pageN=...

router.get(   '/ref/all',   db.getAll_ref); // GET    /ref/all without BODY
router.get(   '/ref/',  db.getSingle_ref);  // GET    /ref/?pId=...&per_pId=... without BODY
router.post(  '/ref',   db.create_ref);     // POST   /ref with BODY: pId=...&per_pId=...&Memo=...
router.put(   '/ref/',  db.update_ref);     // PUT    /ref with BODY: pId=...&per_pId=...&Memo=...
router.delete('/ref/',  db.remove_ref);     // DELETE /ref with BODY: pId=...&per_pId=...

module.exports = router;
